### ISSUE TITLE
cordova-hcp deploy copy all the file, should also use chcpignore

### ISSUE THREAD

**Issue by dongdh** [nordnet/cordova-hot-code-push-cli#49] opened 2016-04-11 12:49 UTC
cordova-hcp deploy copy all the file, should also use chcpignore

**Comment by nikDemyankov** [comment] 2016-04-15 11:59
Yes, you are correct: it seems `deploy` doesn't respect the ignore list. At the moment it is used only for the `build` operation. This should be fixed.

Either way, can you check, that generated `chcp.manifest` file doesn't contain `chcp.manifest` in it? It feels like the issue you are having in https://github.com/nordnet/cordova-hot-code-push/issues/133 is because of this.

Just open via browser `https://path/to/your/content/chcp.manifest` and search for `chcp.manifest` in it. If it's there - remove it.

**Comment by dongdh** [comment] 2016-04-19 07:05
ye, the bug is from manifest file in the manifest file, i added it to ignore list, then it worked.

**Comment by nikDemyankov** [comment] 2016-04-19 07:38
Good, thanks. Also, please check, that `chcp.json` is not in manifest file. These files should be ignored by CLI client by default. Strange, that they are not in your case.

**Comment by davidovich** [comment] 2016-04-29 21:22
@nikDemyankov I have glanced over the code, and if you specify a .chcpigore file, it overrides the default array. see https://github.com/nordnet/cordova-hot-code-push-cli/blob/master/src/context.js#L57

**Comment by nikDemyankov** [comment] 2016-05-02 09:08
@davidovich good catch, thanks :)

**Comment by nikDemyankov** [comment] 2016-05-04 13:29
Released in v1.1.0. Should now work. If not - please, reopen the issue.

**Comment by diegodotta** [comment] 2016-05-26 14:41
I'm using the v1.1.1  and the deploy doesn't respect the .chcpignore or chcp.manifest.

**Comment by nikDemyankov** [comment] 2016-05-26 14:51
@diegodotta Are you running on Windows machine?

**Comment by diegodotta** [comment] 2016-05-26 15:09
Yes, let me try on mac.

**Comment by anthonytvamp** [comment] 2016-08-08 01:37
I can confirm @diegodotta that I'm using v1.1.1 on Mac and deploy still doesn't respect .chcpignore or chcp.manifest.

**Closed** 2018-09-19 10:56 UTC
Labels: bug
